[project]
name = "pylanczos"
version = "2.1.2"
authors = [{ name = "mrcdr" }]
license = "MIT"
description = "Lanczos diagonalization library: Python interface with C++ implementation"
readme = "README.md"
keywords = ["Lanczos", "diagonalization", "C++", "Python"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = ["numpy"]

[project.urls]
Homepage = "https://github.com/mrcdr/pylanczos"
Source = "https://github.com/mrcdr/pylanczos"
Issues = "https://github.com/mrcdr/pylanczos/issues"

[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"
