name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare venv
        run: |
          pip install --upgrade pip
          python -m venv venv
          source ./venv/bin/activate

      - name: Install library
        run: pip install .

      - name: Install test dependencies
        run: pip install scipy coverage

      - name: Execute tests
        run: coverage run --source pylanczos/ -m unittest discover test/ -v

      - name: Generate code coverage data
        run: coverage xml

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
